# Generated by Django 4.1.3 on 2022-11-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_regmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deptmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=300)),
                ('officeno', models.IntegerField()),
            ],
        ),
    ]
