# Generated by Django 4.1.3 on 2022-11-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_deptmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptmodel',
            old_name='officeno',
            new_name='office_no',
        ),
    ]
